package model;

// default package
// Generated 22-abr-2016 1:08:12 by Hibernate Tools 5.1.0.Alpha1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Libro generated by hbm2java
 */
@Entity
@Table(name="factura")
public class Libro implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer libroId;
	private Integer isbn;
	private String titulo;
	private String asignatura;
	private Integer curso;
	private String editorial;
	private Integer estado;
	private Date añoEdicion;
	private Date añoCompra;
	private List<Lote> lotes = new ArrayList<Lote>();
	
	public Libro() {
	}
	
	public Libro(Integer isbn, String titulo, String asignatura, Integer curso, String editorial, Integer estado, Date añoEdicion, Date añoCompra) {
        this.isbn = isbn;
        this.titulo = titulo;
        this.asignatura = asignatura;
        this.curso = curso;
        this.editorial = editorial;
        this.estado = estado;
        this.añoEdicion = añoEdicion;
        this.añoCompra = añoCompra;
    }
	
	public Libro(Integer isbn, String titulo, String asignatura, Integer curso, String editorial, Integer estado, Date añoEdicion, Date añoCompra, List<Lote> lotes) {
       this.isbn = isbn;
       this.titulo = titulo;
       this.asignatura = asignatura;
       this.curso = curso;
       this.editorial = editorial;
       this.estado = estado;
       this.añoEdicion = añoEdicion;
       this.añoCompra = añoCompra;
       this.lotes = lotes;
    }
	
	@Id
    @GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="id", columnDefinition="NUMBER(19)", unique=true, nullable=false, precision=19)
	public Integer getLibroId() {
		return libroId;
	}
	public void setLibroId(Integer libroId) {
		this.libroId = libroId;
	}
	
	@Column(name="ISBN", columnDefinition="NUMBER(11)", nullable=false, precision=11)
	public Integer getIsbn() {
		return this.isbn;
	}
	public void setIsbn(Integer isbn) {
		this.isbn = isbn;
	}
	
	@Column(name="titulo", columnDefinition="VARCHAR2(100 CHAR)", nullable=false, length=100)
	public String getTitulo() {
		return this.titulo;
	}
	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}
	
	@Column(name="asignatura", columnDefinition="VARCHAR2(45 CHAR)", nullable=false, length=45)
	public String getAsignatura() {
		return this.asignatura;
	}
	public void setAsignatura(String asignatura) {
		this.asignatura = asignatura;
	}
	
	@Column(name="curso", columnDefinition="NUMBER(11)", nullable=false, precision=11)
	public Integer getCurso() {
		return this.curso;
	}
	public void setCurso(Integer curso) {
		this.curso = curso;
	}
	
	@Column(name="editorial", columnDefinition="VARCHAR2(45 CHAR)", nullable=false, length=45)
	public String getEditorial() {
		return this.editorial;
	}
	public void setEditorial(String editorial) {
		this.editorial = editorial;
	}
	
	@Column(name="estado", columnDefinition="NUMBER(11)", nullable=false, precision=11)
	public Integer getEstado() {
		return this.estado;
	}
	public void setEstado(Integer estado) {
		this.estado = estado;
	}
	
    @Column(name="año edicion", columnDefinition="DATE", nullable=false)
	public Date getAñoEdicion() {
        return this.añoEdicion;
    }
	public void setAñoEdicion(Date añoEdicion) {
        this.añoEdicion = añoEdicion;
    }
	
    @Column(name="año compra", columnDefinition="DATE", nullable=false)
	public Date getAñoCompra() {
        return this.añoCompra;
    }
	public void setAñoCompra(Date añoCompra) {
        this.añoCompra = añoCompra;
    }
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lotes", nullable=false, insertable=true, updatable=true)
	//TODO
	public List<Lote> getLotes() {
		return this.lotes;
	}
	public void setLotes(List<Lote> lotes) {
		this.lotes = lotes;
	}
}