package model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

// default package
// Generated 22-abr-2016 1:08:12 by Hibernate Tools 5.1.0.Alpha1

/**
 * LoteId generated by hbm2java
 */
@Embeddable
public class LoteId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer prestamoIdPrestamo;
	private String prestamoAlumnoSocioDni;
	private Integer libroIsbn;
	
	public LoteId() {
	}
	
	public LoteId(Integer prestamoIdPrestamo, String prestamoAlumnoSocioDni, Integer libroIsbn) {
		this.prestamoIdPrestamo = prestamoIdPrestamo;
		this.prestamoAlumnoSocioDni = prestamoAlumnoSocioDni;
		this.libroIsbn = libroIsbn;
	}
	
	@Column(name="prestamo_id prestamo", columnDefinition="NUMBER(11)", precision=11, insertable=true, nullable=false, updatable=false)
	public Integer getPrestamoIdPrestamo() {
		return this.prestamoIdPrestamo;
	}
	public void setPrestamoIdPrestamo(Integer prestamoIdPrestamo) {
		this.prestamoIdPrestamo = prestamoIdPrestamo;
	}
	
	@Column(name="prestamo_alumno_socio_DNI", columnDefinition="VARCHAR2(9 CHAR)", nullable=false, length=9)
	public String getPrestamoAlumnoSocioDni() {
		return this.prestamoAlumnoSocioDni;
	}
	public void setPrestamoAlumnoSocioDni(String prestamoAlumnoSocioDni) {
		this.prestamoAlumnoSocioDni = prestamoAlumnoSocioDni;
	}
	
	@Column(name="libro_ISBN", columnDefinition="NUMBER(11)", precision=11, insertable=true, nullable=false, updatable=false)
	public Integer getLibroIsbn() {
		return this.libroIsbn;
	}
	public void setLibroIsbn(Integer libroIsbn) {
		this.libroIsbn = libroIsbn;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoteId))
			return false;
		LoteId castOther = (LoteId) other;

		return (this.getPrestamoIdPrestamo() == castOther.getPrestamoIdPrestamo())
				&& ((this.getPrestamoAlumnoSocioDni() == castOther.getPrestamoAlumnoSocioDni())
						|| (this.getPrestamoAlumnoSocioDni() != null && castOther.getPrestamoAlumnoSocioDni() != null
								&& this.getPrestamoAlumnoSocioDni().equals(castOther.getPrestamoAlumnoSocioDni())))
				&& (this.getLibroIsbn() == castOther.getLibroIsbn());
	}
	
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPrestamoIdPrestamo();
		result = 37 * result + (getPrestamoAlumnoSocioDni() == null ? 0 : this.getPrestamoAlumnoSocioDni().hashCode());
		result = 37 * result + this.getLibroIsbn();
		return result;
	}
}