package model;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// default package
// Generated 22-abr-2016 1:08:12 by Hibernate Tools 5.1.0.Alpha1

/**
 * Lote generated by hbm2java
 */
@Entity
@Table(name="lote")
public class Lote implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private LoteId id;
	private Libro libro;
	private Prestamo prestamo;
	private String estado;
	
	public Lote() {
	}
	
	public Lote(LoteId id, Libro libro, Prestamo prestamo, String estado) {
		this.id = id;
		this.libro = libro;
		this.prestamo = prestamo;
		this.estado = estado;
	}
	
	@EmbeddedId
	public LoteId getId() {
		return this.id;
	}
	public void setId(LoteId id) {
		this.id = id;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="libros", nullable=false, insertable=true, updatable=true)
	//TODO
	public Libro getLibro() {
		return this.libro;
	}
	public void setLibro(Libro libro) {
		this.libro = libro;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prestamos", nullable=false, insertable=true, updatable=true)
	//TODO
	public Prestamo getPrestamo() {
		return this.prestamo;
	}
	public void setPrestamo(Prestamo prestamo) {
		this.prestamo = prestamo;
	}
	
	@Column(name="estado", columnDefinition="VARCHAR2(45 CHAR)", nullable=false, length=45)
	public String getEstado() {
		return this.estado;
	}
	public void setEstado(String estado) {
		this.estado = estado;
	}
}